CREATE DATABASE IF NOT EXISTS APP_MAIN;
CREATE DATABASE IF NOT EXISTS APP_MONITORING;

USE APP_MAIN;

CREATE TABLE login_event (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    login_timestamp DATETIME NOT NULL,
    ip_address VARCHAR(255),
    location VARCHAR(255),
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

USE APP_MONITORING;

CREATE TABLE login_activity (
    id INT AUTO_INCREMENT PRIMARY KEY,
    location VARCHAR(255) NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    login_count INT NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);